version: '3'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: shopping-cart
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      -'5432:5432'
  node-app:
    image: shoppingcart
    ports:
      - '8181:8080'
    depends_on:
      - db
volumes:
  db-data
